Repository devcss122/CP-Solutions, pull requests merged in 2020-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 Add Readme LOGO (#1)
  .github/logo.png
  .github/workflow.yml
  README.md
Labels: Good First PR, hacktoberfest-accepted

#4 Added Codeforces Solutions
  .gitignore
  A1316.java
  A320.java
  A44.java
  A550.java
  A550.py
  A58.java
  A868.java
  A931.java
  A96.java
  B1223.java
  B279.java
  B493.java
  B931.java
  B935.java
  BookReading.java
  C1131.java
  Cards1220A.java
  Digits.java
  FactMod.java
  PeriodicNumber.java
  R427.java
  R468.java
  R501.java
  R51.java
  R589.java
  R590F.java
  R74A.java
  R74E.java
  ReadAFile.class
  ReadFileUsingBR.class
  RenameAFile.class
  ReverseNumber.class
  Table.class
  TablePrinter.class
  TestFile.class
  TestQueue.class
  Tree$Node.class
  Tree.class
  TreeDiagram$Node.class
  TreeDiagram$Trunk.class
  TreePrinter$Node.class
  TreePrinter.class
  VaribleLengthMethod.class
Labels: Great Work!, documentation, enhancement, hacktoberfest-accepted

#6 Create Java Inbuilt GCD Method for Competitive Programming
  Java Inbuilt GCD Method for Competitive Programming
Labels: Good First PR, Great Work!, hacktoberfest-accepted

#7 Project Setup : Rename
  CONTRIBUTING.md
  icpc/2019_azulejosDK.cpp
  icpc/2019_beautifulbridgesDK.cpp
  icpc/2019_checksDK.cpp
  icpc/2019_circularDK.cpp
  icpc/2019_deadendDK.cpp
  icpc/2019_hobsonstrainsDK.cpp
  icpc/2019_karelDK.cpp
  icpc/2019_minigolfDK.cpp
  icpc/2019_trafficblightsDK.cpp
Labels: GOOD PR!, Great Work!, hacktoberfest-accepted

#9 Added Badges (#8)
  README.md
Labels: GOOD PR!, Working PR!, enhancement

#10 Updated Contributing guidelines.
  CONTRIBUTING.md
  README.md
Labels: GOOD PR!, enhancement

#13 Solved Issue (#12)
  py/A1092.py
  py/A754.py
  py/A994.py
  py/B1082.py
  py/B988.py
  py/B994.py
  py/B996.py
Labels: GOOD PR!, Good First PR, enhancement, hacktoberfest-accepted

#14 Added Leetcode Python Questions.
  py/1017.py
  py/1018.py
  py/1019.py
  py/1020.py
  py/1021.py
  py/1022.py
  py/1023.py
  py/1025.py
  py/1026.py
  py/1027.py
  py/1028.py
  py/1029.py
  py/1030.py
  py/1031.py
  py/1032.py
  py/1033.py
  py/1034.py
  py/1035.py
  py/1037.py
  py/1038.py
  py/1039.py
  py/1041.py
  py/1042.py
  py/1043.py
  py/1044.py
  py/1046.py
  py/1047.py
  py/1048.py
  py/1051.py
  py/1052.py
  py/1053.py
  py/1054.py
  py/1064.py
  py/1065.py
  py/1071.py
  py/1072.py
  py/1073.py
Labels: GOOD PR!, Great Work!, enhancement

#15 Added Coderforces Cpp Solutions.
  cpp/bad_ugly_numbers.cpp
  cpp/candies_and_sisters.cpp
  cpp/carousel.cpp
  cpp/divisibility.cpp
  cpp/dreamoon.cpp
  cpp/exercising_walk.cpp
  cpp/filling_diamonds.cpp
  cpp/grade_allocation.cpp
  cpp/kth_beautiful.cpp
  cpp/level_statistics.cpp
  cpp/maximums.cpp
  cpp/middle_class.cpp
  cpp/mysterious.cpp
  cpp/mysterious_optimized.cpp
  cpp/recommendations.cpp
  cpp/sorted_differences.cpp
  cpp/ternary.cpp
Labels: Great Work!, Review Required

#19 added python solution to leetcode 1073
  py/1073.py
Labels: Great Work!, enhancement, hacktoberfest-accepted

#18 James ozjlol patch 1
  java/Autori.java
  java/BatterUp_Kattis.java
  java/HissingMicrophone_Kattis.java
Labels: Good First PR, Great Work!, hacktoberfest-accepted
